# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every week
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    reviewers:
      - 'DyRize'
    labels:
      - 'dependencies'
      - 'dependabot'
    groups:
      core:
        patterns:
          - 'react'
          - 'react-dom'
          - 'next'
      ui:
        patterns:
          - '@radix-ui/*'
          - 'tailwindcss'
          - 'tailwindcss-animate'
          - 'tailwind-merge'
      tooling:
        patterns:
          - 'eslint'
          - 'prettier'
          - 'typescript'
          - 'jest'
          - 'postcss'
          - 'knip'
      storybook:
        patterns:
          - '@storybook/*'
      i18n:
        patterns:
          - 'i18next'
          - 'next-intl'
    target-branch: 'dev'
    open-pull-requests-limit: 20
