# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every week
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    reviewers:
      - 'DyRize'
    labels:
      - 'dependencies'
      - 'dependabot'
    groups:
      core:
        patterns:
          - 'next'
          - 'next-themes'
          - 'react'
          - 'react-dom'
      ui:
        patterns:
          - '@radix-ui/*'
          - 'autoprefixer'
          - 'class-variance-authority'
          - 'clsx'
          - 'tailwind-merge'
          - 'tailwindcss'
          - 'tailwindcss-animate'
          - 'postcss'
      state:
        patterns:
          - 'jotai'
      localization:
        patterns:
          - 'i18next'
          - 'next-intl'
      types:
        patterns:
          - '@types/*'
          - 'typescript'
          - '@total-typescript/ts-reset'
      linting:
        patterns:
          - 'eslint'
          - 'eslint-config-next'
          - 'prettier'
          - 'prettier-plugin-tailwindcss'
      testing:
        patterns:
          - '@testing-library/*'
          - 'jest'
          - 'jest-environment-jsdom'
      storybook:
        patterns:
          - '@chromatic-com/storybook'
          - '@storybook/*'
          - 'storybook'
          - 'eslint-plugin-storybook'
      tools:
        patterns:
          - 'knip'
    target-branch: 'dev'
    open-pull-requests-limit: 20
