import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import GlobalContext from '@contexts/GlobalContext';
import { getMessages } from 'next-intl/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <GlobalContext messages={messages} locale={locale}>
          {children}
        </GlobalContext>
      </body>
    </html>
  );
}
